<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MLambda.AI.Airline.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="MLambda.AI.Airline.Chat" />
    <Using Include="MLambda.AI.Airline.Expert" />
    <Using Include="MLambda.AI.Airline.Llm" />
    <Using Include="MLambda.AI.Airline.Records" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.9.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MLambda.AI.Airline\MLambda.AI.Airline.csproj" />
  </ItemGroup>
</Project>
